---
- name: Check the status of "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT_old" file
  stat:
    path: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT_old"
  register: dat_old_status

- name: Check the status of "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY_old" file
  stat:
    path: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY_old"
  register: key_old_status

- name: Rename PKI DAT file
  command: "mv /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT_old"
  when: not dat_old_status.stat.exists

- name: Rename PKI KEY file
  command: "mv /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY_old"
  when: not key_old_status.stat.exists

- name: Create a new empty PKI DAT file
  ansible.builtin.file:
    path: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT"
    owner: "{{ hana_sid | lower }}adm"
    group: sapsys
    mode: '0644'
    state: touch
  when: not dat_old_status.stat.exists

- name: Create a new empty PKI KEY file
  ansible.builtin.file:
    path: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY"
    owner: "{{ hana_sid | lower }}adm"
    group: sapsys
    mode: '0640'
    state: touch
  when: not key_old_status.stat.exists

- name: Replace the content of SSFS_{{ hana_sid | upper }}.DAT from secondary SAP HANA system withe the content of SSFS_{{ hana_sid | upper }}.DAT from primary SAP HANA system
  ansible.builtin.copy:
    content: "{{ hostvars['db_host_primary']['ssfs_data']['content'] | b64decode }}"
    dest: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT"

- name: Replace the content of SSFS_{{ hana_sid | upper }}.KEY from secondary SAP HANA system withe the content of SSFS_{{ hana_sid | upper }}.KEY from primary SAP HANA system
  ansible.builtin.copy:
    content: "{{ hostvars['db_host_primary']['ssfs_key']['content'] | b64decode }}"
    dest: "/usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY"
...
