---
  - name: Replace the content of /etc/hosts from secondary SAP HANA system withe the content of /etc/hosts from primary SAP HANA system
    ansible.builtin.copy:
      content: "{{ hostvars['db_host_primary']['etc_hosts']['content'] | b64decode }}"
      dest: /etc/hosts
      owner: root
      group: root
...
