---
- hosts: db_host_dr
  gather_facts: yes
  vars: 
    hana_sid: "{{ hostvars['db_host_primary']['hana_sid'] }}"
    hana_sysno: "{{ hostvars['db_host_primary']['hana_sysno'] }}"
    hana_tenants: "{{ hostvars['db_host_primary']['hana_tenants'] }}"
  pre_tasks:
    - name: Import playbook variables
      include_vars: "saphana-vars.yml"
  roles:
    - enablesaphanadr_secondary
...
