---

- name: Create a temporary directory to store the PKY
  ansible.builtin.file:
    path: "/tmp/{{ hdb_hostname_primary }}/pki"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: '0755'
  delegate_to: localhost

- name: Get primary node PKI
  fetch:
    src: "{{ pki_key }}"
    dest: "/tmp/{{ hdb_hostname_primary }}/pki/"
    flat: yes
  loop:
    - /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/data/SSFS_{{ hana_sid | upper }}.DAT
    - /usr/sap/{{ hana_sid | upper }}/SYS/global/security/rsecssfs/key/SSFS_{{ hana_sid | upper }}.KEY
  loop_control:
    loop_var: pki_key
...
